require_relative 'item.rb'
class BasicSalesTax
  def initialize(tax_rate = 10)
    @tax_rate = tax_rate
    @tax_free_list = prepare_tax_free_list
  end

  def calculate_tax(item, total_price)
    if @tax_free_list.any? { |e| item.name.downcase.include? e.downcase }
      0
    else
      total_price *  @tax_rate / 100
    end
  end

  private

  def prepare_tax_free_list
    # I find a example tax free list from a random gov website

    # The method is too long... well, in real world the method should
    # be replaced by a query of ActiveRecord
    foods = ['Arnold Palmer Half & Half',
             'Artificial sweeteners',
             'Baby food',
             'Bakery products',
             'Baking products',
             'Beefamato',
             'Boost',
             'Bouillon cubes',
             'Bread',
             'Brownies',
             'Butter',
             'Cereals',
             'Chicory',
             'Chocolate',
             'Clamato Juice Cocktail',
             'Cocoa',
             'Coconut',
             'Coffee',
             'Coffee creamers',
             'Condiments',
             'Cookies',
             'Crackers',
             'Cupcakes',
             'Dehydrated fruit',
             'Dehydrated vegetables',
             'Diet foods',
             'Diet substitutes',
             'Diet supplements',
             'Doughnuts',
             'Dressings',
             'Eggs and egg products',
             'Ensure',
             'Fats',
             'Fish and fish products',
             'Flavorings',
             'Flour',
             'Food coloring',
             'Frozen desserts',
             'Frozen dinners ',
             'Fruit',
             'Grain products',
             'Granola bars',
             'Gravies',
             'Health bars',
             'Health food',
             'Health supplements',
             'Herbs',
             'Honey',
             'Ice cream',
             'Iced coffee',
             'Iced tea',
             'Iced tea mix',
             'Instant breakfast mix',
             'Jams',
             'Jelling agents',
             'Jellies',
             'Ketchup',
             'Lard',
             'Leavening agents',
             'Liquid diet products',
             'Mayonnaise',
             'Meats and meat products',
             'Milk and milk products',
             'Mustard',
             'Non-stick cooking sprays',
             'Nutrament',
             'Nuts and nut products',
             'Oils',
             'Oleomargarine',
             'Olives',
             'Ovaltine',
             'Peanut butter',
             'Peanuts',
             'Pepper',
             'Popcorn',
             'Potato chips',
             'Poultry',
             'Poultry products',
             'Preservatives',
             'Pretzels',
             'Quik',
             'Relishes',
             'Salad dressing mixes',
             'Salad dressings',
             'Salt',
             'Sandwich spreads',
             'Sauces',
             'Seafood',
             'Seasonings',
             'Sesame seeds',
             'Sherbet',
             'Shortening',
             'Slim-Fast',
             'Soup',
             'Spices',
             'Starch',
             'Start',
             'Sugar',
             'Sugar substitutes',
             'Sunflower seeds',
             'Syrups',
             'Tang',
             'Tea',
             'Vanilla extract',
             'Vegetables',
             'Vegetable juices',
             'Vegetable oils',
             'V8 Juice',
             'Vitamins',
             'Yeast']

    medical_products = ['Acne',
                        'Allergy',
                        'Analgesics',
                        'Antacids',
                        'diarrhea',
                        'nausea',
                        'fungal',
                        'rheumatic',
                        'vomiting',
                        'bacterial',
                        'sanitizer',
                        'wipessoap',
                        'biotic',
                        'Antihistamines',
                        'Antiperspirants',
                        'Antiseptic',
                        'Bronchodilator',
                        'asthmatic',
                        'Cold',
                        'Headache',
                        'Cough',
                        'Dandruff',
                        'Dental',
                        'Ear',
                        'Eye',
                        'Hemorrhoid',
                        'Insect bite',
                        'Laxatives',
                        'Nicotine',
                        'Pain',
                        'Sedatives',
                        'Toothache']
    books = ['book'] # I give up :(
    books + medical_products + foods
  end
end
